### ISSUE TITLE
Vendor Information

### ISSUE THREAD

**Issue by Pauldro** [cptechinc/soft-crm#108]
The Uninvoiced table needs another table row with the class `last-section-row` in between POs 

On that note, if you'd like to come up with a better way / or even style it differently a way to separate rows like this, go ahead, but let me know.

The costing doesn't seem to work.

The ones that aren't for sure done 
Unreleased
24 Month Summary

Remove the console.log line from vend-info.js on line 62

**Comment by bbullemer** [comment]
Do you mean you want the 'POnbr and 'EACH' to have the row with that class between them?

**Comment by Pauldro** [comment]
Upload your _init.js.php

**Comment by bbullemer** [comment]
Uploaded

**Comment by Pauldro** [comment]
So after each totals line put a table row with the class last-section-row for spacing.
![image](https://user-images.githubusercontent.com/5648224/32863759-33093bc6-ca22-11e7-9055-949a40bd2cc9.png)

**Comment by bbullemer** [comment]
I haven't changed my code and there is a line under totals. It will not let me take a screen shot on my computer of the remote desktop. I'm using mozilla developer browser.

**Comment by Pauldro** [comment]
@bbullemer There's a row there but it's not being occupied by any table cells so it won't render correctly. 

Also Look at the code between Lines 47-67, You are hard coding looking for columns, the columns are being provided to you in the json file.
https://github.com/cptechinc/soft-crm/blob/1b6e79fae5f04f14f8942d1c5dd639402d22ccad/site/templates/content/vend-information/vend-uninvoiced.php#L41-L67

Also re look at the header columns, you're only showing 4 of the actual header columns needed. Your line with the using the count -- is making it fail. You'll have to try something different here.

This is a great start, now you just need to figure out how to do this with a less hardcoding.
