### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rbecker50** [cptechinc/soft-crm#11]
Got this error after hitting the documents Icon - still worked and I could open the doc, but this error looked serious

![image](https://user-images.githubusercontent.com/31143592/29879769-ad2b6bc0-8d6b-11e7-98da-844c81b409ee.png)

**Comment by Pauldro** [comment]
Fixed in https://github.com/cptechinc/soft-crm/commit/83c2a2ff4cddd872218fbedd288a9012d41bbf0b
