### ISSUE TITLE
Design a Search Orders Page

### ISSUE THREAD

**Issue by Pauldro** [cptechinc/soft-crm#142]
[example](https://www.walmart.com/search/?query=everlast%20punching%20bag&typeahead=everlast)

Create and design a search orders page. The orders should list the same way as they currently do. But they don't have to be in a panel. What we want to do is create the sidebar to filter/search our orders like the walmart link above. Don't go too crazy with the css, we want to keep it simple.

**Comment by bbullemer** [comment]
When you're on the dashboard and open orders, once you press the search
orders button it will come to this new page? or when you open the orders on
the dashboard will it expand to something like this?

**Comment by Pauldro** [comment]
@bbullemer this will be its own page. There will be a link to it, so it's easier to search/filter orders. This just lets us create a cleaner way to filter and search by allowing us space to have a sidebar

**Comment by Pauldro** [comment]
Decided to integrate into the panel 5612476901b7599b9eea2c700688f0820669a310
