### ISSUE TITLE
Editing Details

### ISSUE THREAD

**Issue by Pauldro** [cptechinc/soft-crm#145]
We have 3 things to deal with CartDetail, SalesOrderDetail, QuoteDetail
Make a new branch called edit-detail, upload vendor/cptechinc and site/templates/

##CartDetail
**site\templates\content\ajax\load\edit-detail-router.php**
We will now be using the _CartDetail_ Class found in **vendor\cptechinc\dpluso-processwire-classes\src\Model\CartDetail.class.php**

change 
`$linedetail = getcartline(session_id(), $linenbr, false)` to
`$linedetail = CartDetail::load(session_id(), $linenbr);`

Now in the file that is included 
site\templates\content\edit\pricing\edit-pricing-form.php and the file it also includes you'll change the $linedetail to access items as an object instead of an array

Now you'll change the file 
**site\templates\redir\cart-redir.php**
for the case update-line
You'll want to change
`$cartdetail = getcartline(session_id(), $linenbr, false)`  to `$cartdetail = CartDetail::load(session_id(), $linenbr);`
And change all the $cartdetail to set values as object properties and not array values,
Then you'll change the line with `$session->sql = edit_cartline(session_id(), $cartdetail, false);` to 
`$session->sql = $cartdetail->update();`

## SalesOrderDetail
Do the same as above the files you want to look at are 
**site\templates\content\ajax\load\edit-detail-router.php**
**site\templates\redir\orders-redir.php** CASE update-line
**vendor\cptechinc\dpluso-processwire-classes\src\Model\SalesOrderDetail.class.php**
Now the class file for this one needs the missing CRUD functions from CartDetail  copy the missing functions then make sure they work. The has changes function will be different because the load function needs different parameters. The update function will need to call a different _dbfunc.php function which you will create called update_orderdetail() and make sure the function behaves as it should look at update_cartdetail for reference, use querybuilder. 

##QuoteDetail
Do the same as above the files you want to look at are 
**site\templates\content\ajax\load\edit-detail-router.php**
**site\templates\redir\quotes-redir.php** CASE update-line

At the end of it all the end of the form it tries to access $linedetail['can-edit'] change that to $linedetail->can_edit();
Make sure to test this extensively since this is something Stat will be using constantly so we want this as bug free as possible. 

Ask if you need help

**Comment by bbullemer** [comment]
@Pauldro For some reason I cannot call on the quote class. I just committed changes, so maybe you can look over them and give me a little guidance.

**Comment by Pauldro** [comment]
Ok, where are you trying to call the quote class? and where can I go to recreate the issue?

**Comment by bbullemer** [comment]
If you create a quote and then try to edit, the modal that loads has the error "trying to get property of non-object" over any field calling the object properties.

**Comment by Pauldro** [comment]
@bbullemer look at get_quotedetail( in _dbfunc.php 
You have it listed as 
`get_quotedetail($sessionID, $linenbr, $qnbr, $debug = false)`
It should be
`get_quotedetail($sessionID, **$qnbr, $linenbr,** $debug = false)`

**Comment by bbullemer** [comment]
@Pauldro Are you working on any of the cart files? I'm getting an error of "Call to undefined function getcarthead()"

**Comment by bbullemer** [comment]
@Pauldro Nevermind, figured it out.
