### ISSUE TITLE
QUOTES

### ISSUE THREAD

**Issue by rbecker50** [cptechinc/soft-crm#6]
ONE MORE.   WOULD IT BE POSSIBLE TO CREATE A VIEW QUOTE - JUST LIKE YOU DO ON THE ORDERS - SAY ON THE DASHBOARD

![image](https://user-images.githubusercontent.com/31143592/29669842-61834d2a-88aa-11e7-8bc3-19fc974e0c79.png)

**Comment by Pauldro** [comment]
Quotes have that already
