### ISSUE TITLE
Can't edit an item in cart

### ISSUE THREAD

**Issue by rbecker50** [cptechinc/soft-crm#88]
Just sits and spins when I try to edit a line after it was added

![image](https://user-images.githubusercontent.com/31143592/32057689-993ebbbe-ba2d-11e7-93c9-7cc26d5f4405.png)

**Comment by rbecker50** [comment]
Same thing happens when i try to edit the quote items.

**Comment by Pauldro** [comment]
fixed in d3fda0347fc4b3c4da7834683164a34996231f09
